# Generated by Django 5.1.4 on 2026-10-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_company_gst_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('INVALID', 'Invalid'), ('INACTIVE', 'Inactive'), ('FAILED', 'Failed')], max_length=20)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('gst_status', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('taxpayer_type', models.CharField(blank=True, max_length=100)),
                ('business_constitution', models.CharField(blank=True, max_length=100)),
                ('principal_address', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_verifications', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
