# Generated by Django 5.1.4 on 2026-10-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_plans_and_supplier_roles'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplace', '0021_plan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='marketplace.requirement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_receipts', to='accounts.manufacturerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'received_at'], name='plans_rfqre_supplie_916ff0_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'requirement'), name='rfqreceipt_once_per_supplier')],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('field', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.consumerprofile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.manufacturerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['buyer'], name='plans_store_buyer_i_92503e_idx'), models.Index(fields=['supplier'], name='plans_store_supplie_89b64b_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field'), name='storedfile_one_per_field')],
            },
        ),
    ]
