# Generated by Django 5.1.4 on 2026-09-22 03:32

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('submitted', 'Submitted'), ('quoted', 'Quoted'), ('quote_selected', 'Quote Selected'), ('in_production', 'In Production'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.consumerprofile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.manufacturerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='marketplace.order')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.manufacturerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.quote'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('rfq_desc', models.CharField(max_length=400, verbose_name='Name')),
                ('nda_required', models.BooleanField(default=False)),
                ('quote_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar')], max_length=50)),
                ('request_reason', models.CharField(choices=[('new_product', 'New product'), ('second_source', 'Second source'), ('supplier_failure', 'Supplier failure'), ('benchmarking', 'Benchmarking'), ('other', 'Other')], max_length=50)),
                ('parts', models.IntegerField(default=1)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='requirement_files/')),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Production', 'Production'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='marketplace.requirement'),
        ),
        migrations.AddField(
            model_name='order',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.requirement'),
        ),
        migrations.CreateModel(
            name='RequirementPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=100, verbose_name='Name')),
                ('Part_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('technology', models.CharField(choices=[('Anodizing', 'Anodizing'), ('Full-range turning', 'Full-range turning'), ('Turning', 'Turning'), ('Milling', 'Milling')], max_length=50)),
                ('Material', models.CharField(choices=[('Structural steel', 'Structural steel'), ('Stainless steel', 'Stainless steel'), ('Aluminium', 'Aluminium'), ('Case hardening', 'Case hardening')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='requirement_files/parts/')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_parts', to='marketplace.requirement')),
            ],
        ),
    ]
