# Generated by Django 5.1.4 on 2026-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='extracted_data',
        ),
    ]
