# Generated by Django 5.1.4 on 2026-09-23 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_materialcapability_manufacturerprofile_about_and_more'),
        ('marketplace', '0002_remove_requirement_extracted_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, choices=[('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('fedex', 'FedEx'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_other',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='eway_bill_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='production_stage',
            field=models.CharField(choices=[('order_confirmed', 'Order confirmed'), ('material_received', 'Material received'), ('machining', 'Machining'), ('finishing_qc', 'Finishing & QC'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='order_confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='lead_time_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='lead_time_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('100_advance', '100% advance'), ('50_50', '50% advance / 50% on delivery'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('against_lc', 'Against LC')], max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_file',
            field=models.FileField(blank=True, null=True, upload_to='quote_files/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tooling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductionStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('to_stage', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_stage_history', to='marketplace.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='order_updates/photos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='order_updates/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_items', to='marketplace.order')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marketplace.requirement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_questions', to='accounts.manufacturerprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQDecline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declines', to='marketplace.requirement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_declines', to='accounts.manufacturerprofile')),
            ],
            options={
                'unique_together': {('requirement', 'supplier')},
            },
        ),
    ]
