# Generated by Django 5.1.4 on 2026-09-24 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_materialcapability_manufacturerprofile_about_and_more'),
        ('marketplace', '0003_order_courier_order_courier_other_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='marketplace.requirement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='accounts.manufacturerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('requirement', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
