# Generated by Django 5.1.4 on 2026-09-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_sync_requirement_part_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qc_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'Status change'), ('stage', 'Production stage change')], max_length=10)),
                ('from_value', models.CharField(blank=True, max_length=30)),
                ('to_value', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.order')),
            ],
            options={
                'ordering': ['changed_at', 'pk'],
                'indexes': [models.Index(fields=['order', 'kind'], name='marketplace_order_i_eb0f5d_idx')],
            },
        ),
    ]
