# Generated by Django 5.1.4 on 2026-09-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_move_history_qc_and_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstagehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='qcchecklistitem',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='qcchecklistitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='requirementquestion',
            name='asked_by',
        ),
        migrations.RemoveField(
            model_name='requirementquestion',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='requirementquestion',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='ProductionStageHistory',
        ),
        migrations.DeleteModel(
            name='QCChecklistItem',
        ),
        migrations.DeleteModel(
            name='RequirementQuestion',
        ),
    ]
