# Generated by Django 5.1.4 on 2026-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_retired_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='revised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='revision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
