# Generated by Django 5.1.4 on 2026-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_quote_revision_and_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='revision_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
