# Generated by Django 5.1.4 on 2026-09-25 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_quote_revision_declined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting suppliers'), ('applied', 'Applied'), ('withdrawn', 'Withdrawn by buyer'), ('closed', 'Closed when the RFQ was awarded')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='marketplace.requirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmendmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting for supplier'), ('rejected', 'Supplier rejected the changes'), ('accepted', 'New pricing sent — waiting for buyer'), ('buyer_accepted', 'Buyer accepted the new pricing'), ('buyer_declined', 'Buyer kept the original details'), ('closed', 'Closed')], default='pending', max_length=16)),
                ('supplier_note', models.TextField(blank=True)),
                ('quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tooling_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lead_time_value', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks')], max_length=10)),
                ('payment_terms', models.CharField(blank=True, choices=[('100_advance', '100% advance'), ('50_50', '50% advance / 50% on delivery'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('against_lc', 'Against LC')], max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_decided_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_responses', to='marketplace.quote')),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='marketplace.requirementamendment')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('amendment', 'quote')},
            },
        ),
    ]
