# Generated by Django 5.1.4 on 2026-09-26 13:30

from django.db import migrations, models


# Starting values only, so reports work on day one. Staff keep them
# current in the admin (Marketplace > Exchange rates).
STARTING_RATES = {
    'USD': '88.0', 'EUR': '103.0', 'JPY': '0.60', 'GBP': '118.0', 'AUD': '58.0',
    'CAD': '64.0', 'CHF': '110.0', 'CNY': '12.3', 'SEK': '9.3', 'NZD': '52.0',
}


def seed_rates(apps, schema_editor):
    ExchangeRate = apps.get_model('marketplace', 'ExchangeRate')
    for currency, rate in STARTING_RATES.items():
        ExchangeRate.objects.get_or_create(currency=currency, defaults={'inr_per_unit': rate})


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_supplier_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar')], max_length=3, unique=True)),
                ('inr_per_unit', models.DecimalField(decimal_places=6, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.RunPython(seed_rates, migrations.RunPython.noop),
    ]
