# Generated by Django 5.1.4 on 2026-09-26 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_exchange_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_key', models.CharField(max_length=40)),
                ('kind', models.CharField(max_length=10)),
                ('financial_year', models.CharField(max_length=4)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issuer_key', 'kind', 'financial_year'), name='unique_document_sequence')],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('po', 'Purchase order'), ('invoice', 'Tax invoice')], max_length=10)),
                ('number', models.CharField(max_length=16)),
                ('issuer_key', models.CharField(max_length=40)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.JSONField()),
                ('buyer', models.JSONField()),
                ('details', models.JSONField()),
                ('currency', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pdf', models.FileField(blank=True, upload_to='order_documents/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='marketplace.order')),
            ],
            options={
                'ordering': ['issued_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'kind'), name='one_document_of_each_kind_per_order'), models.UniqueConstraint(fields=('issuer_key', 'kind', 'number'), name='unique_document_number_per_issuer')],
            },
        ),
    ]
