# Generated by Django 5.1.4 on 2026-09-28 18:06

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_order_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='pdf',
            field=models.FileField(blank=True, upload_to=marketplace.models.order_document_path),
        ),
    ]
