# Generated by Django 5.1.4 on 2026-09-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_lut'),
        ('marketplace', '0018_alter_orderdocument_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementNDAAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_acceptances', to='marketplace.requirement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_acceptances', to='accounts.manufacturerprofile')),
            ],
            options={
                'unique_together': {('requirement', 'supplier')},
            },
        ),
    ]
