# Generated by Django 5.1.4 on 2026-10-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_submitted_at(apps, schema_editor):
    """Quotes already sent count as submitted when they were created."""
    Quote = apps.get_model('marketplace', 'Quote')
    Quote.objects.filter(is_draft=False, submitted_at__isnull=True).update(submitted_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_plans_and_supplier_roles'),
        ('marketplace', '0020_teams_and_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tooling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lead_time_value', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_unit', models.CharField(blank=True, max_length=10)),
                ('payment_terms', models.CharField(blank=True, max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='marketplace.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processes', models.JSONField(blank=True, default=list)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_alert_preference', to='accounts.manufacturerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tooling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lead_time_value', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10)),
                ('payment_terms', models.CharField(blank=True, choices=[('100_advance', '100% advance'), ('50_50', '50% advance / 50% on delivery'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('against_lc', 'Against LC')], max_length=20)),
                ('valid_for_days', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_templates', to='accounts.manufacturerprofile')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'name'), name='quotetemplate_unique_name')],
            },
        ),
        migrations.RunPython(backfill_submitted_at, migrations.RunPython.noop),
    ]
