# Generated by Django 5.1.4 on 2026-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofile',
            name='certificates',
            field=models.CharField(blank=True, choices=[('', 'Not certified'), ('ISO-TS 16949:2009', 'ISO-TS 16949:2009'), ('ISO 9001:2015', 'ISO 9001:2015'), ('ISO 9001:2008', 'ISO 9001:2008'), ('ISO 14001', 'ISO 14001'), ('OHSAS 18000', 'OHSAS 18000'), ('SA 8000', 'SA 8000'), ('DIN EN 1090', 'DIN EN 1090'), ('ISO-TS 16949:2002', 'ISO-TS 16949:2002'), ('IATF 16949:2016', 'IATF 16949:2016'), ('VDA 6.1', 'VDA 6.1'), ('VDA 6.2', 'VDA 6.2'), ('VDA 6.4', 'VDA 6.4'), ('EN ISO 13485', 'EN ISO 13485'), ('JAR 145', 'JAR 145'), ('QSF-A', 'QSF-A'), ('QSF-B', 'QSF-B'), ('PART 145', 'PART 145'), ('DIN 18800-7:2008 Class A-C', 'DIN 18800-7:2008 Class A-C (minor welding cert.)'), ('DIN 18800-7:2008 Class D/E', 'DIN 18800-7:2008 Class D/E (major welding cert.)'), ('DIN EN ISO 3834', 'DIN EN ISO 3834'), ('EN ISO 9001', 'EN ISO 9001'), ('EN ISO 14001', 'EN ISO 14001')], max_length=40, null=True),
        ),
    ]
