# Generated by Django 5.1.4 on 2026-09-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_manufacturerprofile_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('gst_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('gst_verified', models.BooleanField(default=False)),
                ('gst_verified_at', models.DateTimeField(blank=True, null=True)),
                ('registered_address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('cin', models.CharField(blank=True, max_length=21, null=True, unique=True)),
                ('mca_status', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('llp', 'LLP'), ('partnership', 'Partnership'), ('proprietorship', 'Proprietorship'), ('other', 'Other')], max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Manual Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['gstin'], name='accounts_co_gstin_235327_idx'), models.Index(fields=['verification_status'], name='accounts_co_verific_ee63a0_idx')],
            },
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_profile', to='accounts.company'),
        ),
    ]
