# Generated by Django 5.1.4 on 2026-09-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_manufacturerprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('structural_steel', 'Structural steel'), ('stainless_steel', 'Stainless steel'), ('aluminium', 'Aluminium'), ('case_hardening', 'Case hardening'), ('titanium', 'Titanium'), ('brass', 'Brass'), ('copper', 'Copper'), ('plastics', 'Plastics / polymers')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='accepting_rfqs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='accounts.manufacturingtech'),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer/covers/'),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='minimum_order_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='typical_lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Typical days from order confirmation to dispatch', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtech',
            name='technology_type',
            field=models.CharField(choices=[('milling', 'Milling'), ('5_axis_milling', '5-axis milling machines'), ('form_milling', 'Form milling (3D)'), ('full_range_milling', 'Full-range milling (including turning)'), ('hsc_milling', 'HSC milling'), ('deep_hole_drilling', 'Deep-hole drilling'), ('ultrasonic_milling', 'Ultrasonic milling'), ('engraver_milling', 'Engraver milling'), ('turning', 'Turning'), ('full_range_turning', 'Full-range turning'), ('anodizing', 'Anodizing'), ('cnc_turning', 'CNC turning'), ('cmm_inspection', 'CMM inspection'), ('sheet_metal', 'Sheet metal fabrication'), ('injection_molding', 'Injection molding'), ('anodizing_partner', 'Anodizing (via partner)')], default='milling', max_length=50),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='manufacturer/certifications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.manufacturerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=100)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('work_envelope', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='accounts.manufacturerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manufacturer/photos/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.manufacturerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturerprofile',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='accounts.materialcapability'),
        ),
    ]
