# Generated by Django 5.1.4 on 2026-09-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_materialcapability_manufacturerprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='pending_plan_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pending_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
