# Generated by Django 5.1.4 on 2026-09-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_pending_upgrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManufacturingSector',
        ),
    ]
