# Generated by Django 5.1.4 on 2026-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_manufacturingsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lut_reference',
            field=models.CharField(blank=True, max_length=30, verbose_name='LUT ARN'),
        ),
        migrations.AddField(
            model_name='company',
            name='lut_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='LUT valid until'),
        ),
    ]
