# Generated by Django 5.1.4 on 2026-10-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumer_profile', to='accounts.company'),
        ),
    ]
