# Generated by Django 5.1.4 on 2026-10-03 09:33

from django.db import migrations, models


PLAN_MAP = {'basic': 'free', 'standard': 'starter', 'enterprise': 'business'}
MONTHLY_PRICE = {'free': 0, 'starter': 999, 'business': 2999}


def forwards(apps, schema_editor):
    """Old plans move to their new names (basic -> Free, standard -> Starter,
    enterprise -> Business), billed monthly at the new prices; on supplier
    companies, Procurement members become Sales."""
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    for old, new in PLAN_MAP.items():
        SubscriptionPlan.objects.filter(plan_type=old).update(plan_type=new, price=MONTHLY_PRICE[new])
        SubscriptionPlan.objects.filter(pending_plan_type=old).update(pending_plan_type=new, pending_billing_cycle='monthly')
    for model_name in ('TeamMember', 'TeamInvitation'):
        model = apps.get_model('accounts', model_name)
        model.objects.filter(supplier__isnull=False, role='procurement').update(role='sales')


def backwards(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    for old, new in PLAN_MAP.items():
        SubscriptionPlan.objects.filter(plan_type=new).update(plan_type=old)
        SubscriptionPlan.objects.filter(pending_plan_type=new).update(pending_plan_type=old)
    for model_name in ('TeamMember', 'TeamInvitation'):
        model = apps.get_model('accounts', model_name)
        model.objects.filter(role__in=['sales', 'operations']).update(role='procurement')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_owner_admin_procurement_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='rfq_limit',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pending_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pending_plan_type',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('procurement', 'Procurement'), ('sales', 'Sales'), ('operations', 'Operations'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('procurement', 'Procurement'), ('sales', 'Sales'), ('operations', 'Operations'), ('viewer', 'Viewer')], default='procurement', max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
