# Generated by Django 5.1.4 on 2026-10-03 17:25

import datetime

import django.utils.timezone
from django.db import migrations, models

PERIOD_DAYS = {'monthly': 30, 'yearly': 365}


def to_timestamps(apps, schema_editor):
    """start_date/end_date were dates; the lifecycle needs exact times.
    A paid plan keeps its end date (end of that day) and renews from then;
    one already past its end date is left to lapse to Free; one staff set
    with no end date gets a single period from now. A plan requested but
    never paid for (pending_*) becomes the plan chosen at sign-up, which
    the owner can pay for from the billing tab."""
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    tz = django.utils.timezone.get_current_timezone()
    now = django.utils.timezone.now()
    for sub in SubscriptionPlan.objects.all():
        start = datetime.datetime.combine(sub.start_date, datetime.time.min, tzinfo=tz) if sub.start_date else now
        sub.started_at = sub.current_period_start = min(start, now)
        if sub.plan_type != 'free':
            if sub.end_date:
                sub.expires_at = datetime.datetime.combine(sub.end_date, datetime.time.max, tzinfo=tz)
            else:
                sub.expires_at = now + datetime.timedelta(days=PERIOD_DAYS.get(sub.billing_cycle, 30))
            sub.auto_renew = sub.expires_at > now
        if sub.pending_plan_type and sub.pending_plan_type != sub.plan_type:
            sub.intended_plan_type = sub.pending_plan_type
            sub.intended_billing_cycle = sub.pending_billing_cycle or 'monthly'
        sub.save()


def to_dates(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    for sub in SubscriptionPlan.objects.all():
        sub.start_date = sub.started_at.date()
        sub.end_date = sub.expires_at.date() if sub.expires_at else None
        sub.pending_plan_type = sub.intended_plan_type
        sub.pending_billing_cycle = sub.intended_billing_cycle
        sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_plans_and_supplier_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gateway_mandate_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='intended_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='intended_plan_type',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business')], max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='renewal_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='scheduled_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='scheduled_plan_type',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business')], max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(to_timestamps, to_dates),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pending_billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pending_plan_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pending_requested_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='start_date',
        ),
    ]
