# Generated by Django 5.1.4 on 2026-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_subscription_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='reminder_before_sent_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='reminder_day_sent_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
